
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/
server:
  port: 7001
spring:
  application:
    name: service-hello
  zipkin:
    base-url: http://localhost:7000/
    # 若在同一个注册中心的话可以启用自动发现，省略base-url
    locator:
      discovery:
        enabled: true #自动发现
  sleuth:
    sampler:
      percentage: 1.0
