server:
  port: 4002
spring:
  application:
    name: server-customer-feign-hystrix

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/

feign:
  hystrix:
    enabled: true

