#server:
#  port: 6000
#spring:
#  application:
#    name: config-server
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/shared
server:
  port: 6000
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhijunma/spring-cloud-config.git
          search-paths: spring-cloud-config.git
          username: zhijunma
          password: mzjandzjl520
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka/